'use client'

import { useState } from "react";

export default function FAQ() {
  const faqsLeft = [
    {
      question: "Why should I choose Safari Marketing Pro?",
      answer:
        "You should select SMP because we have a unique and inventive marketing strategy that ensures the success of each campaign. It’s been more than 12 years we have been adding value to small to medium size safari business owners, making them brands and getting them direct clients.",
    },
    {
      question: "Can You Provide references?",
      answer: "Yes, we have a 300+ clients ( like Falcon Safaris,748 Air services LTD,Go2 Africa, Mahlatini Luxury Travel, TANAPA, Rhino Africa, Easy Travels, Altezza Travel, Zara Tours ETC..) who have agreed to be contacted by potential clients in order to give feedback on our work and service. We will happily arrange an introduction meeting.",
    },
    {
      question: "What I can expect when I choose you for my SAFARI Business?",
      answer: "Sir, We will definitely help you in increasing the no. of bookings like the way we have helped more than 300+ African safari companies. We will work as a bridge between your potential customers and your services and make them reach to you in all possible online marketing ways.",
    },
    {
        question: "What common Marketing problems Organic Marketing can fix ?",
        answer: "There are many common problems that safari businesses face with an organic marketing campaign. They include: Unqualified Safari LeadsHigh Marketing CostsLow Sales Through our Organic Marketing strategies, you can attract qualified traffic to boost your safari businesses’ bookings. Leads generated by search have a close rate of nearly 15%, which is much higher than traditional methods.",
      },
      {
        question: "How does the payment work and how much does it cost?",                                               
        answer: "We always agree payment in advance of a project being started, and any changes in budget will be fully communicated and agreed in writing in advance. We have instalment options, For Website: 50% before start the work and 50% before live the website.For Marketing: 50% before start the work and 50% after 6 month of the work contract. ",
      },
  ];

  const faqsRight = [
    {
      question: "Don't own my Website. What are your Options?",
      answer: "To be present on the market and meet your client’s directly is one of the great feelings, and for that, you have to meet the minimum requirements like having a world class safari website that will work as the face of your safari business. With a website puts full stop on all those hurdles and minimizes the cost.",
    },
    {
      question: "Can you help us with reporting?",
      answer: "<div class='py-4'>Yes. We will provide insightful monthly analytics reports tailored to your safari business and your objectives.</div><div class='pt-4'>You will have a dedicated project manager.</div><br/>He/ She will be the contact point for your project and will create a what’s app group where every step will updates you on how far the project has been completed and any of the work progress.<div class='pt-4'>The Team will be available for 24*7 to support you</div>",
    },
    {
      question: "What are the Advantages of 360° Marketing services?",
      answer:
        "360° marketing services help you increase brand awareness, brand loyalty and drive sales inquiries and bookings for your safari business. The main advantage of 360° marketing is that it helps you measure success, performance and results of all the activities across all platforms in a very cost-effective way.",
    },
    {
        question: "How do I choose a digital agency for my safari company?",
        answer:
          "<div class='pb-2'>Every safari companies are different goals.</div> <div class='pb-2'>So the first step in choosing the right marketing company is understanding your goals and what you hope to achieve by working with one.</div><div class='pb-2>These are some factors will make sure that you don’t end up choosing the wrong digital partner, losing time and money.</div><div class='pb-2>- The credibility of Digital Marketing Agency</div><div class='pb-2'>- Planning Your Budget and Understanding Your Needs and gives you a Tailored Strategy</div><div class='pb-2'>- A sizable portfolio and/or list of past clients</div><div class=''>- Social proof and a strong industry reputation</div>",
      },
      {
        question: "What are the benefits of hiring a digital marketing agency?",
        answer:
          "Having a marketing agency as a partner means you can focus on all the most important aspects of growing your safari business. Sure, that includes awesome digital marketing, but you can take a lot of that off your shoulders when there’s a team of reliable, accountable experts doing what needs to be done.",
      },
  ];

  const [openLeftIndex, setOpenLeftIndex] = useState(null);
  const [openRightIndex, setOpenRightIndex] = useState(null);

  const toggleLeftFAQ = (index) => {
    setOpenLeftIndex(openLeftIndex === index ? null : index);
  };

  const toggleRightFAQ = (index) => {
    setOpenRightIndex(openRightIndex === index ? null : index);
  };

  return (
    <div className=" max-w-[1200px] mx-auto flex flex-col items-center px-4 py-10">
      <h1 className="text-5xl font-bold px-10 text-blue-600 mb-8 text-center">
        Frequently Asked Questions Of African Safari Operators
      </h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10 w-full max-w-4xl">
        {/* Left Column */}
        <div>
          {faqsLeft.map((faq, index) => (
            <div
              key={index}
              onClick={() => toggleLeftFAQ(index)}
              className="bg-white shadow-md rounded-lg p-6 mb-6 text-gray-700 cursor-pointer hover:shadow-lg transition-shadow"
            >
              <p className="font-medium flex justify-between items-center">
                {faq.question}
                <span className={`ml-4 transform ${openLeftIndex === index ? "rotate-180" : ""}`}>
                  ▼
                </span>
              </p>
              {openLeftIndex === index && (
                <p className="mt-2 text-gray-600">{faq.answer}</p>
              )}
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div>
          {faqsRight.map((faq, index) => (
            <div
              key={index}
              onClick={() => toggleRightFAQ(index)}
              className="bg-white shadow-md rounded-lg p-6 mb-6 text-gray-700 cursor-pointer hover:shadow-lg transition-shadow"
            >
              <p className="font-medium flex justify-between items-center">
                {faq.question}
                <span className={`ml-4 transform ${openRightIndex === index ? "rotate-180" : ""}`}>
                  ▼
                </span>
              </p>
              {openRightIndex === index && (
                <p className="mt-2 text-gray-600"
                dangerouslySetInnerHTML={{ __html: faq.answer }}
                />
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
